platformio run --verbose --environment alfawise_it_mbl_U20_classicui_d3v11
platformio run --verbose --environment alfawise_it_mbl_U20_classicui_d3v12
platformio run --verbose --environment alfawise_it_mbl_U20_classicui_d3v19
platformio run --verbose --environment alfawise_it_mbl_U20_colorui_d3v11
platformio run --verbose --environment alfawise_it_mbl_U20_colorui_d3v12
platformio run --verbose --environment alfawise_it_mbl_U20_colorui_d3v19
platformio run --verbose --environment alfawise_it_abl_U20_classicui_d3v11
platformio run --verbose --environment alfawise_it_abl_U20_classicui_d3v12
platformio run --verbose --environment alfawise_it_abl_U20_classicui_d3v19
platformio run --verbose --environment alfawise_it_abl_U20_colorui_d3v11
platformio run --verbose --environment alfawise_it_abl_U20_colorui_d3v12
platformio run --verbose --environment alfawise_it_abl_U20_colorui_d3v19
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_classicui_d3v11
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_classicui_d3v12
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_classicui_d3v19
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_colorui_d3v11
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_colorui_d3v12
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_colorui_d3v19

platformio run --verbose --environment alfawise_it_mbl_U20_PLUS_classicui_d3v11
platformio run --verbose --environment alfawise_it_mbl_U20_PLUS_classicui_d3v12
platformio run --verbose --environment alfawise_it_mbl_U20_PLUS_classicui_d3v19
platformio run --verbose --environment alfawise_it_mbl_U20_PLUS_colorui_d3v11
platformio run --verbose --environment alfawise_it_mbl_U20_PLUS_colorui_d3v12
platformio run --verbose --environment alfawise_it_mbl_U20_PLUS_colorui_d3v19
platformio run --verbose --environment alfawise_it_abl_U20_PLUS_classicui_d3v11
platformio run --verbose --environment alfawise_it_abl_U20_PLUS_classicui_d3v12
platformio run --verbose --environment alfawise_it_abl_U20_PLUS_classicui_d3v19
platformio run --verbose --environment alfawise_it_abl_U20_PLUS_colorui_d3v11
platformio run --verbose --environment alfawise_it_abl_U20_PLUS_colorui_d3v12
platformio run --verbose --environment alfawise_it_abl_U20_PLUS_colorui_d3v19
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_PLUS_classicui_d3v11
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_PLUS_classicui_d3v12
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_PLUS_classicui_d3v19
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_PLUS_colorui_d3v11
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_PLUS_colorui_d3v12
platformio run --verbose --environment alfawise_it_mbl_DUALE_U20_PLUS_colorui_d3v19

platformio run --verbose --environment alfawise_it_mbl_U30_classicui_d3v11
platformio run --verbose --environment alfawise_it_mbl_U30_classicui_d3v12
platformio run --verbose --environment alfawise_it_mbl_U30_classicui_d3v19
platformio run --verbose --environment alfawise_it_mbl_U30_colorui_d3v11
platformio run --verbose --environment alfawise_it_mbl_U30_colorui_d3v12
platformio run --verbose --environment alfawise_it_mbl_U30_colorui_d3v19
platformio run --verbose --environment alfawise_it_abl_U30_classicui_d3v11
platformio run --verbose --environment alfawise_it_abl_U30_classicui_d3v12
platformio run --verbose --environment alfawise_it_abl_U30_classicui_d3v19
platformio run --verbose --environment alfawise_it_abl_U30_colorui_d3v11
platformio run --verbose --environment alfawise_it_abl_U30_colorui_d3v12
platformio run --verbose --environment alfawise_it_abl_U30_colorui_d3v19
platformio run --verbose --environment alfawise_it_mbl_DUALE_U30_classicui_d3v11
platformio run --verbose --environment alfawise_it_mbl_DUALE_U30_classicui_d3v12
platformio run --verbose --environment alfawise_it_mbl_DUALE_U30_classicui_d3v19
platformio run --verbose --environment alfawise_it_mbl_DUALE_U30_colorui_d3v11
platformio run --verbose --environment alfawise_it_mbl_DUALE_U30_colorui_d3v12
platformio run --verbose --environment alfawise_it_mbl_DUALE_U30_colorui_d3v19

platformio run --verbose --environment alfawise_en_mbl_U20_classicui_d3v11
platformio run --verbose --environment alfawise_en_mbl_U20_classicui_d3v12
platformio run --verbose --environment alfawise_en_mbl_U20_classicui_d3v19
platformio run --verbose --environment alfawise_en_mbl_U20_colorui_d3v11
platformio run --verbose --environment alfawise_en_mbl_U20_colorui_d3v12
platformio run --verbose --environment alfawise_en_mbl_U20_colorui_d3v19
platformio run --verbose --environment alfawise_en_abl_U20_classicui_d3v11
platformio run --verbose --environment alfawise_en_abl_U20_classicui_d3v12
platformio run --verbose --environment alfawise_en_abl_U20_classicui_d3v19
platformio run --verbose --environment alfawise_en_abl_U20_colorui_d3v11
platformio run --verbose --environment alfawise_en_abl_U20_colorui_d3v12
platformio run --verbose --environment alfawise_en_abl_U20_colorui_d3v19
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_classicui_d3v11
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_classicui_d3v12
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_classicui_d3v19
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_colorui_d3v11
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_colorui_d3v12
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_colorui_d3v19

platformio run --verbose --environment alfawise_en_mbl_U20_PLUS_classicui_d3v11
platformio run --verbose --environment alfawise_en_mbl_U20_PLUS_classicui_d3v12
platformio run --verbose --environment alfawise_en_mbl_U20_PLUS_classicui_d3v19
platformio run --verbose --environment alfawise_en_mbl_U20_PLUS_colorui_d3v11
platformio run --verbose --environment alfawise_en_mbl_U20_PLUS_colorui_d3v12
platformio run --verbose --environment alfawise_en_mbl_U20_PLUS_colorui_d3v19
platformio run --verbose --environment alfawise_en_abl_U20_PLUS_classicui_d3v11
platformio run --verbose --environment alfawise_en_abl_U20_PLUS_classicui_d3v12
platformio run --verbose --environment alfawise_en_abl_U20_PLUS_classicui_d3v19
platformio run --verbose --environment alfawise_en_abl_U20_PLUS_colorui_d3v11
platformio run --verbose --environment alfawise_en_abl_U20_PLUS_colorui_d3v12
platformio run --verbose --environment alfawise_en_abl_U20_PLUS_colorui_d3v19
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_PLUS_classicui_d3v11
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_PLUS_classicui_d3v12
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_PLUS_classicui_d3v19
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_PLUS_colorui_d3v11
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_PLUS_colorui_d3v12
platformio run --verbose --environment alfawise_en_mbl_DUALE_U20_PLUS_colorui_d3v19

platformio run --verbose --environment alfawise_en_mbl_U30_classicui_d3v11
platformio run --verbose --environment alfawise_en_mbl_U30_classicui_d3v12
platformio run --verbose --environment alfawise_en_mbl_U30_classicui_d3v19
platformio run --verbose --environment alfawise_en_mbl_U30_colorui_d3v11
platformio run --verbose --environment alfawise_en_mbl_U30_colorui_d3v12
platformio run --verbose --environment alfawise_en_mbl_U30_colorui_d3v19
platformio run --verbose --environment alfawise_en_abl_U30_classicui_d3v11
platformio run --verbose --environment alfawise_en_abl_U30_classicui_d3v12
platformio run --verbose --environment alfawise_en_abl_U30_classicui_d3v19
platformio run --verbose --environment alfawise_en_abl_U30_colorui_d3v11
platformio run --verbose --environment alfawise_en_abl_U30_colorui_d3v12
platformio run --verbose --environment alfawise_en_abl_U30_colorui_d3v19
platformio run --verbose --environment alfawise_en_mbl_DUALE_U30_classicui_d3v11
platformio run --verbose --environment alfawise_en_mbl_DUALE_U30_classicui_d3v12
platformio run --verbose --environment alfawise_en_mbl_DUALE_U30_classicui_d3v19
platformio run --verbose --environment alfawise_en_mbl_DUALE_U30_colorui_d3v11
platformio run --verbose --environment alfawise_en_mbl_DUALE_U30_colorui_d3v12
platformio run --verbose --environment alfawise_en_mbl_DUALE_U30_colorui_d3v19